# Bindings for GD classes.

Addr = int

def CCObject_retain(self: Addr): ...
def CCObject_release(self: Addr): ...

def FLAlertLayer_create(title: str, desc: str, btn: str) -> Addr: ...
def FLAlertLayer_show(self: Addr): ...
