# Bindings for geode.

from typing import Callable

Addr = int

def get_base() -> Addr: ...
def get_cocos_base() -> Addr: ...

def log_debug(msg: str): ...
def log_info(msg: str): ...
def log_warn(msg: str): ...
def log_error(msg: str): ...

def mod_get() -> Addr: ...
def mod_get_version(self: Addr) -> str: ...
def mod_patch(self: Addr, address: Addr, bytes: bytes) -> Addr: ...
def mod_add_hook(self: Addr, function: str, detour: Callable) -> Addr: ...

def loader_get() -> Addr: ...

def Notification_create(text: str, icon: int, time: float) -> Addr: ...
def Notification_show(self: Addr) -> Addr: ...