# Internal utilities for pygeode.

from typing import Any

Addr = int

def call_original(name: str, *args) -> Any: ...
def mbo_string(ptr: Addr, offset: int) -> str: ...
def mbo_int(ptr: Addr, offset: int) -> int: ...
def mbo_bool(ptr: Addr, offset: int) -> bool: ...
def mbo_ptr(ptr: Addr, offset: int) -> Addr: ...
